INSERT INTO genres (genre) VALUES ('Comedy');
INSERT INTO genres (genre) VALUES ('Fantasy');
INSERT INTO genres (genre) VALUES ('Adveture');
INSERT INTO genres (genre) VALUES ('Biographical');
INSERT INTO genres (genre) VALUES ('Criminal');
INSERT INTO genres (genre) VALUES ('Natural');
INSERT INTO genres (genre) VALUES ('Historical');
INSERT INTO genres (genre) VALUES ('Detective');
INSERT INTO books (title, author, publisher, count, amount) VALUES ('Tytul1', 'Autor1', 'Wydawnictwo1', 15, 14);
INSERT INTO books_genres (books_id, genres_id) VALUES (1, 2);
INSERT INTO books_genres (books_id, genres_id) VALUES (1, 4);
INSERT INTO books_genres (books_id, genres_id) VALUES (1, 1);
INSERT INTO books (title, author, publisher, count, amount) VALUES ('Tytul2', 'Autor1', 'Wydawnictwo2', 11, 6);
INSERT INTO books_genres (books_id, genres_id) VALUES (2, 6);
INSERT INTO books_genres (books_id, genres_id) VALUES (2, 4);
INSERT INTO books_genres (books_id, genres_id) VALUES (2, 2);
INSERT INTO books (title, author, publisher, count, amount) VALUES ('Tytul6', 'Autor1', 'Wydawnictwo1', 15, 15);
INSERT INTO books_genres (books_id, genres_id) VALUES (3, 6);
INSERT INTO books_genres (books_id, genres_id) VALUES (3, 3);
INSERT INTO books (title, author, publisher, count, amount) VALUES ('Tytul1', 'Autor2', 'Wydawnictwo1', 10, 4);
INSERT INTO books_genres (books_id, genres_id) VALUES (4, 8);
INSERT INTO books (title, author, publisher, count, amount) VALUES ('Tytul4', 'Autor1', 'Wydawnictwooooo', 12, 9);
INSERT INTO books_genres (books_id, genres_id) VALUES (5, 8);
INSERT INTO books_genres (books_id, genres_id) VALUES (5, 1);
INSERT INTO books_genres (books_id, genres_id) VALUES (5, 2);
INSERT INTO books_genres (books_id, genres_id) VALUES (5, 5);
INSERT INTO books (title, author, publisher, count, amount) VALUES ('Tytul1', 'Autor3', 'Chyba', 5, 1);
INSERT INTO books_genres (books_id, genres_id) VALUES (6, 3);
INSERT INTO books_genres (books_id, genres_id) VALUES (6, 4);
INSERT INTO books_genres (books_id, genres_id) VALUES (6, 2);
INSERT INTO books (title, author, publisher, count, amount) VALUES ('Tytul23', 'Autor2', 'Nie', 17, 17);
INSERT INTO books_genres (books_id, genres_id) VALUES (7, 7);
INSERT INTO books_genres (books_id, genres_id) VALUES (7, 6);
INSERT INTO books_genres (books_id, genres_id) VALUES (7, 2);
INSERT INTO books_genres (books_id, genres_id) VALUES (7, 5);
INSERT INTO books_genres (books_id, genres_id) VALUES (7, 1);
INSERT INTO books (title, author, publisher, count, amount) VALUES ('Tytul11', 'Autor121', 'Niespodzianka', 3, 0);
INSERT INTO books_genres (books_id, genres_id) VALUES (8, 2);
INSERT INTO books (title, author, publisher, count, amount) VALUES ('Tytul123', 'Autor122', 'Wydawnictwosdfvasd', 2, 2);
INSERT INTO books_genres (books_id, genres_id) VALUES (9, 2);
INSERT INTO books_genres (books_id, genres_id) VALUES (9, 4);
INSERT INTO books_genres (books_id, genres_id) VALUES (9, 1);
INSERT INTO books (title, author, publisher, count, amount) VALUES ('Tytul16', 'Autor121', 'Wydawnictrqwe', 11, 2);
INSERT INTO books_genres (books_id, genres_id) VALUES (10, 2);
INSERT INTO books_genres (books_id, genres_id) VALUES (10, 8);
INSERT INTO books (title, author, publisher, count, amount) VALUES ('Tytul1432', 'Autor122', 'Nie', 7, 2);
INSERT INTO books_genres (books_id, genres_id) VALUES (11, 1);
INSERT INTO books_genres (books_id, genres_id) VALUES (11, 6);
INSERT INTO books (title, author, publisher, count, amount) VALUES ('Tytul1', 'Autor1', 'Wydawnictwo1', 6, 4);
INSERT INTO books_genres (books_id, genres_id) VALUES (12, 7);
INSERT INTO books_genres (books_id, genres_id) VALUES (12, 3);